# Generated by Django 5.0.3 on 2024-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('background_poster', models.ImageField(blank=True, null=True, upload_to='background_posters/')),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
