# Generated by Django 5.0.3 on 2024-04-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20240415_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='background_poster',
            field=models.ImageField(blank=True, default='background_posters/default_background_poster.jpg', null=True, upload_to='background_posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='movie_posters/default_poster.jpg', null=True, upload_to='movie_posters/'),
        ),
    ]
