# Generated by Django 5.0.3 on 2024-04-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_background_poster_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='background_poster',
            field=models.ImageField(default='background_posters/default_background_poster.jpg', upload_to='background_posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='movie_posters/default_poster.jpg', upload_to='movie_posters/'),
        ),
    ]
