# Generated by Django 5.0.3 on 2024-04-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_background_poster_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='background_poster',
            field=models.ImageField(default='https://t4.ftcdn.net/jpg/05/49/86/39/360_F_549863991_6yPKI08MG7JiZX83tMHlhDtd6XLFAMce.jpg', upload_to='background_posters/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='https://s.studiobinder.com/wp-content/uploads/2017/12/Movie-Poster-Template-Dark-with-Image.jpg?x81279', upload_to='movie_posters/'),
        ),
    ]
