# Generated by Django 5.0.3 on 2024-04-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_sequence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='sequence_id',
            field=models.IntegerField(default=1),
        ),
    ]
